### ISSUE TITLE
published to id前5位不是0，请问是哪里设置错了？

### ISSUE THREAD

**Issue by slin784478709** [ubuygold/go-noss#17]
![微信图片_20240104224938](https://github.com/ubuygold/go-noss/assets/30861126/a0112a81-6476-405f-92af-b70ec8bb3f7a)

**Comment by ndcc5** [comment]
一样

**Comment by 1770697081** [comment]
一样，不知道哪里出问题，不知道是不是私钥转换出问题了

**Comment by ubuygold** [comment]
公私钥转换错误，都需要转换，详情看readme
