### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by skyMetaverse** [ubuygold/go-noss#22]
<img width="661" alt="Snipaste_2024-01-05_11-28-23" src="https://github.com/ubuygold/go-noss/assets/103470651/c4c89f44-f84e-4679-855a-f5c5b8567630">

<img width="697" alt="Snipaste_2024-01-05_11-28-34" src="https://github.com/ubuygold/go-noss/assets/103470651/7fe8b665-104f-4132-bc8f-183f933666bb">

内存会随着脚本运行时间不断增加，直到脚本被killed

![WechatIMG220](https://github.com/ubuygold/go-noss/assets/103470651/ebceaafc-0eea-4f9b-b42e-bfcc661fa77e)

**Comment by co-star** [comment]
我也是同样的问题

**Comment by jiushu666** [comment]
感觉单线程循环的就够了

**Comment by qyjgg** [comment]
我也遇到了

**Comment by cateegit** [comment]
一样

**Comment by dusmart** [comment]
go routine 泄漏导致的
许多 routine 中 mine 函数的 select 卡住了

**Comment by kargoo** [comment]
go func() {
		//for {
		select {
		case <-ctx.Done():
			return
		default:
			evCopy := ev
			evCopy, err := Generate(evCopy, difficulty)
			if err != nil {
				// fmt.Println(err)
				atomic.AddInt32(&currentWorkers, -1)
				return
			}
			foundEvent <- evCopy
		}
		//}
	}()
	
	将for循环注释掉，foundEvent得到事件后，mine函数处理后退出，这个routine也应该退出。

**Comment by ubuygold** [comment]
谢谢提醒，这段代码大改过，原来的策略是对一个BlockNumber/eventId对进行多协程计算；后面发现难度太低没有必要，所以改多协程去抓最新的blockNumber/eventId对计算，这个for可能是忘删了。

**Comment by kargoo** [comment]
notFoundEvent := make(chan nostr.Event, 1)
	go func() {
		//for {
		select {
		case <-ctx.Done():
			return
		default:
			evCopy := ev
			evCopy, err := Generate(evCopy, difficulty)
			if err != nil {
				// fmt.Println(err)
				//atomic.AddInt32(&currentWorkers, -1)
				notFoundEvent <- evCopy
				return
			}
			foundEvent <- evCopy
		}
		//}
	}()

	select {
	case <-notFoundEvent:
	case evNew := <-foundEvent:
              ... ...
	case <-ctx.Done():
		fmt.Print("done")
	}
	加个notFoundEvent，屏蔽掉//atomic.AddInt32(&currentWorkers, -1)，发现内存不再增加了

**Comment by ubuygold** [comment]
已修复
