### ISSUE TITLE
linux又如何运行呢？

### ISSUE THREAD

**Issue by xsm19** [ubuygold/go-noss#4]
大佬，求解答

**Comment by ubuygold** [comment]
你都用linux了还不会编译golang吗。。。下载golang环境安装，进项目文件夹,go get，go run ./main.go

**Comment by xsm19** [comment]
对不起我是傻逼

pk=nsec1
sk=d206716728720208f12432c9c42f95ea522b2b1df55f9d08c57bfc30d2e9b127
numberOfWorkers=8

再打扰大佬一下，这个nsec1私钥也要转换吗

**Comment by ubuygold** [comment]
> 大佬，求解答

要把npub和nsec都转换成16进制形式，还有你刚把你私钥发出来了，我给你把回复删了

**Comment by xsm19** [comment]
好的，那是公钥，非常感谢大佬，大佬2024发大财，身体健康万事如意。
