### ISSUE TITLE
194行打印输出,其中,evNew.ID 永久是""空字符串,这是正常的吗?

### ISSUE THREAD

**Issue by seakingii** [ubuygold/go-noss#5]
194行打印输出,其中,evNew.ID 永久是""空字符串,这是正常的吗?
fmt.Println(nostr.Now().Time(), "spend: ", spendTime, "!!!!!!!!!!!!!!!!!!!!!published to:", evNew.ID)
===================================================================

比如以下这条输出:
2024-01-04 19:37:12 +0800 CST spend:  782.4714ms !!!!!!!!!!!!!!!!!!!!!published to:

**Comment by ubuygold** [comment]
不正常，说明你的公私钥配置错误。需要把NPUB和NSEC去指定网站上转换好再放进来。

**Comment by seakingii** [comment]
感谢!使用 
https://nostrcheck.me/converter/
转换后,能正常输出 published to: 0000 ...........这样的字符串了.

还有个小问题,如果挖到了,工具是不是没有输出挖到的信息?

**Comment by ubuygold** [comment]
暂时没有做检测
