### ISSUE TITLE
提交全部失败呢

### ISSUE THREAD

**Issue by kingdancing** [ubuygold/go-noss#6]
抓包看了下提交的post请求全是403呢

**Comment by ubuygold** [comment]
环境复现下？

**Comment by kingdancing** [comment]
> 环境复现下？

mac下，
![WX20240104-195916@2x](https://github.com/ubuygold/go-noss/assets/6369026/39ef0454-f4ac-40bd-b3c0-50dc5b477ee9)

**Comment by kingdancing** [comment]
> 环境复现下？

好了，被Cloudflare拦截了，你这个post header里面要加个useragent，不然默认是goclient会被拦截

**Comment by ubuygold** [comment]
感谢，我看一下

**Comment by ubuygold** [comment]
我本地抓包没加UA也能200？
